<?php

namespace WebAwardsBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     * Retourne le un tableau de commentaire dont la limite est determiner avec le nbComment
     * @param $idProject
     * @param $nbComment
     * @return array
     */
    public function getCommentsById($idProject, $nbComment){
        $nbComment = $nbComment*5;
        $query = $this->createQueryBuilder('c')
            ->where('c.idProject = '.$idProject.'')
            ->setMaxResults($nbComment)
            ->getQuery();

        $resp = $query->getResult();

        return $resp;
    }
}
