<?php

namespace WebAwardsBundle\Repository;

/**
 * Projects_TagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Projects_TagsRepository extends \Doctrine\ORM\EntityRepository
{
}
