<?php

namespace WebAwardsBundle\Repository;

/**
 * Users_VotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users_VotesRepository extends \Doctrine\ORM\EntityRepository
{
}
