<?php

namespace WebAwardsBundle\Repository;

/**
 * WinnersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnersRepository extends \Doctrine\ORM\EntityRepository
{
}
