homepage:
  path: /
  defaults: { _controller: WebAwardsBundle:Project:index}

web_awards:
    resource: "@WebAwardsBundle/Controller/"
    type:     annotation
    prefix:   /
logout:
    path: /logout
condition:
    path: /condition
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    condition.html.twig
evaluation:
    path: /evaluation
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    evaluation.html.twig