# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
                  chain:
                      providers: [our_db_provider, in_memory]
        our_db_provider:
                    entity:
                        class: WebAwardsBundle:User
                        property: username
                        # if you're using multiple entity managers
                        # manager_name: customer
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$aabu98fd.l60phldkU.WAeDwgzqiv1IcaF.EndURJuAhGllFgzTv.
                        roles: 'ROLE_ADMIN'

    encoders:
            Symfony\Component\Security\Core\User\User: bcrypt
            WebAwardsBundle\Entity\User:
                        algorithm: bcrypt
    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #http_basic: ~
            #pattern:    ^/
            #provider: our_db_provider
            form_login:
              login_path: login
              check_path: login


            # Log out user
            logout:
                path:   /logout
                target: /

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
